const formConfig = {
  hiddenFields: [
    /ga_/,
    /utm_/,
    /current lead/,
    /hidden/,
    /hide/,
    /alliance referral/,
    /asset /,
    /contact_type/,
    /lead record type/,
    /gclid/,
  ],
  partialHiddenFields: [/partner country/, /partner company/],
  usPhoneFormatCountries: ["United States", "Canada"],
  gaMeta: [
    {
      name: "ga_user_id__c",
      id: "ga-user-id",
    },
    {
      name: "ga_user_each_id__c",
      id: "ga-user-each-id",
    },
    {
      name: "ga_cookie_id__c",
      id: "ga-cookie-id",
    },
  ],
  errorMessages: [
    { field: "Email", message: "Please enter a valid company email" },
    {
      field: "Phone Number",
      message: "Please enter a valid phone number",
    },
  ],
  blockedContactFormCountries: [
    "Afghanistan",
    "Albania",
    "Belarus",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Myanmar",
    "Central African Republic",
    "China",
    "Congo, the Democratic Republic of the",
    "Croatia",
    "Cuba",
    "Ethiopia",
    "Hong Kong",
    "Iran",
    "Iraq",
    "Lebanon",
    "Libya",
    "Macedonia, the former Yugoslav Republic of",
    "Mali",
    "Montenegro",
    "North Korea",
    "Nicaragua",
    "Russia",
    "Serbia",
    "Slovenia",
    "Somalia",
    "South Sudan",
    "Sudan",
    "Syria",
    "Ukraine",
    "Venezuela",
    "Yemen",
    "Zimbabwe",
  ],
  countries: [
    "Country (Company HQ)",
    "United States",
    "United Kingdom",
    "Australia",
    "Canada",
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia, Plurinational State of",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo, the Democratic Republic of the",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote d’Ivoire",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia, the former Yugoslav Republic of",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
  states: [
    "State (Company HQ)",
    "Alaska",
    "Alabama",
    "Arkansas",
    "Arizona",
    "California",
    "Colorado",
    "Connecticut",
    "District of Columbia",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Iowa",
    "Idaho",
    "Illinois",
    "Indiana",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Massachusetts",
    "Maryland",
    "Maine",
    "Michigan",
    "Minnesota",
    "Missouri",
    "Mississippi",
    "Montana",
    "North Carolina",
    "North Dakota",
    "Nebraska",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "Nevada",
    "New York",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Virginia",
    "Vermont",
    "Washington",
    "Wisconsin",
    "West Virginia",
    "Wyoming",
  ],
  employees: [
    "# of Employees",
    "0-49",
    "50-200",
    "201-500",
    "501-1,000",
    "1001-2000",
    "2kto5k",
    "5000+",
  ],
  crmSolutions: [
    "Current CRM Solution",
    "Not Yet Verified",
    "None",
    "Base",
    "Copper",
    "Freshworks",
    "HelpScout",
    "Highrise CRM",
    "Home Grown",
    "Intercom",
    "Kustomer",
    "Microsoft Dynamics",
    "Oracle Right Now",
    "Pipedrive",
    "Salesforce",
    "Zendesk",
    "Zoho",
    "Other",
    "Hubspot",
    "Pega",
    "Multiple",
  ],
  preferredMasterAgent: [
    "Preferred Master Agent",
    "Appsmart",
    "Avant",
    "Intelisys",
    "Jenne",
    "PlanetOne",
    "Sandler Partners",
    "TCG",
    "Telarus",
    "Undecided",
  ],
  partnerAreaOfInterest: [
    "Partner Area of Interest",
    "Cloud Distributor",
    "Reseller Partner",
    "Referral Partner",
    "Delivery Partner",
    "Alliance Partner",
    "Technology Partner",
    "Integrator",
    "Master Agent",
    "Strategic Partner",
  ],
  certificationType: [
    "Select a Certification Type",
    "UJET Certified Delivery Partner Program",
    "UJET Advisor Certification Program",
    "UJET Reseller Certification Program",
  ],
  dealRegistrationUtmDefaults: [
    { slug: "google", utmDefault: "deal_reg_google" },
    { slug: "kustomer", utmDefault: "deal_reg_kustomer" },
    { slug: "playvox", utmDefault: "deal_reg_playvox" },
    { slug: "acqueon", utmDefault: "deal_reg_acqueon" },
    { slug: "aws", utmDefault: "deal_reg_aws" },
    { slug: "calabrio", utmDefault: "deal_reg_calabrio" },
    { slug: "intercom", utmDefault: "deal_reg_intercom" },
    { slug: "observe-ai", utmDefault: "deal_reg_observe" },
    { slug: "oracle", utmDefault: "deal_reg_oracle" },
    { slug: "successkpi", utmDefault: "deal_reg_successKPI" },
    { slug: "zendesk", utmDefault: "deal_reg_zendesk" },
    { slug: "assembled", utmDefault: "deal_reg_assembled" },
  ],
  contactUsFieldOrder: [
    /first name/,
    /last name/,
    /email/,
    /job/,
    /company/,
    /# of agents/,
    /country/,
    /state/,
    /phone/,
  ],
  dealRegistrationFieldOrder: [
    /first name/,
    /last name/,
    /job/,
    /^email/,
    /^company name/,
    /employees/,
    /country/,
    /state/,
    /city/,
    /^phone/,
  ],
  landingPageFieldOrder: [
    /first name/,
    /last name/,
    /email/,
    /job/,
    /company/,
    /# of agents/,
    /country/,
    /state/,
    /phone/,
  ],
  channelRequestFieldOrder: [
    /first name/,
    /last name/,
    /job/,
    /^company name/,
    /^email/,
    /company hq country/,
    /company hq state/,
    /company hq city/,
    /^phone/,
    /employees/,
    /channel pain point/,
    /current crm solution/,
    /current contact center solution software/,
    /# of licenses/,
    /opportunity details/,
    /partner company name/,
    /partner full name/,
    /partner title/,
    /partner email/,
    /partner country/,
    /partner company state/,
    /partner company city/,
    /partner phone/,
    /preferred master agent/,
    /promo code/,
  ],
  webinarFieldOrder: [
    /first name/,
    /last name/,
    /email/,

    /job/,
    /company/,
    /# of agents/,
    /country/,
    /state/,
    /phone/,
  ],
  blogSubscriptionFieldOrder: [/email/, /country/],
  partnerRequestFieldOrder: [
    /first name/,
    /last name/,
    /job/,
    /partner area of interest/,
    /company/,
    /email/,

    /country/,
    /state/,
    /phone/,
  ],
  googleContactFieldOrder: [
    /first name/,
    /last name/,
    /email/,
    /job/,
    /company/,
    /# of agents/,

    /country/,
    /state/,
    /city/,
    /phone/,
  ],
  defaultFieldOrder: [
    /first name/,
    /last name/,
    /email/,

    /country/,
    /state/,
    /phone/,
  ],
};

export default formConfig;
