pipeline {
    agent any
    options {
        timestamps()
    }

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }

        stage('setup') {
            steps {
                sh '''
                    _ci/setup
                '''
            }
            post {
                failure {
                    sh '''
                        _ci/cleanup
                    '''
                }
            }
        }

        stage('test') {
            steps {
                sh '''
                    _ci/test
                '''
            }
            post {
                failure {
                    sh '''
                        _ci/cleanup
                    '''
                }
            }
        }

        stage('cleanup') {
            steps {
                sh '''
                    _ci/cleanup
                '''
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}

// vim: syntax=groovy :
